name: CallerWorkflow

on:
  workflow_dispatch:

jobs:
  reusable_job:
    name: Write to Environment
    uses: ./.github/workflows/reusable.yml
  
  read_env:
    runs-on: ubuntu-latest
    needs: reusable_job
    steps:
      - name: Read from Environment
        run: |
          echo "${{ needs.reusable_job.outputs.my_file }}"