name: CallerWorkflow

on:
  workflow_dispatch:

jobs:
  reusable_job:
    name: Write to Environment
    uses: ./.github/workflows/reusable.yml
  
  read_env:
    name: Read Output
    runs-on: ubuntu-latest
    needs: reusable_job
    steps:
      - name: Read from Output
        run: |
          my_file=$(echo "${{ needs.reusable_job.outputs.my_file }}" | tr '\n' '\\n')
          echo "$my_file"