name: CallerWorkflow

on:
  workflow_dispatch:

jobs:
  reusable_job:
    name: Get File Content
    uses: ./.github/workflows/reusable.yml
  
  read_env:
    name: Read Output
    runs-on: self-hosted
    needs: reusable_job
    steps:
      - name: Read from Output
        run: |
          my_file="${{ needs.reusable_job.outputs.my_file }}"
          echo -e "$my_file"