name: ReusableWorkflow

on:
  workflow_call:
    outputs:
      my_file:
        value: ${{ jobs.write_output.outputs.file }}

env:
  KEY_FILE_NAME: 'myfile.properties'

jobs:
  write_output:
    name: Write Output
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.get_file.outputs.my_file}}
    steps:
      - name: Write to Environment
        id: get_file
        run: |
          cat << 'EOF' > $KEY_FILE_NAME
          GIT_ACCESS_TOKEN=abcdtoken
          MAVEN_REPO_URL=https://example.com/repo/maven-snapshots
          EOF
          cat $KEY_FILE_NAME
          ##
          #KEY_FILE=$(cat <<EOF
          #GIT_ACCESS_TOKEN=abcdtoken
          #MAVEN_REPO_URL=https://example.com/repo/maven-snapshots
          #EOF
          #)
          ##
          #echo "GIT_ACCESS_TOKEN=abcdtoken" >> $KEY_FILE_NAME
          #echo "MAVEN_REPO_URL=https://example.com/repo/maven-snapshots" >> $KEY_FILE_NAME
          ##
          keyfile=$(<$KEY_FILE_NAME)
          keyfile_flat=$(echo "$keyfile" | tr '\n' '\\n')
          echo "my_file=$keyfile_flat" >> $GITHUB_OUTPUT
