name: ReusableWorkflow

on:
  workflow_call:
    outputs:
      my_file:
        value: ${{ jobs.write_output.outputs.file }}

env:
  KEY_FILE_NAME: 'myfile.properties'

jobs:
  write_output:
    name: Write Output
    runs-on: self-hosted
    outputs:
      file: ${{ steps.get_file.outputs.file}}
    steps:
      - name: Write to Output
        id: get_file
        run: |
          cat << 'EOF' > $KEY_FILE_NAME
          GIT_ACCESS_TOKEN=abcdtoken
          MAVEN_REPO_URL=https://example.com/repo/maven-snapshots
          EOF
          cat $KEY_FILE_NAME
          ##
          keyfile=$(<$KEY_FILE_NAME)
          echo "${keyfile//$'\n'/\\n}"
          keyfile_flat="${keyfile//$'\n'/\\n}"
          echo "::add-mask::$keyfile_flat"
          echo "file=$keyfile_flat" >> $GITHUB_OUTPUT